[project]
name = "my-news-briefing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.12.0",
    "bitsandbytes>=0.49.0",
    "gtts>=2.5.4",
    "langchain-google-genai>=4.1.3",
    "llama-cpp-python>=0.3.16",
    "peft>=0.18.0",
    "pydub>=0.25.1",
    "speechrecognition>=3.14.5",
    "streamlit>=1.52.2",
    "torch>=2.9.1",
    "transformers>=4.57.3",
]
